# Generated by Django 4.1.3 on 2022-12-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zip',
            field=models.IntegerField(max_length=5, null=True),
        ),
    ]
